### ISSUE TITLE
Upload 0.2.0

### ISSUE THREAD

**Issue by ReAzem** [influxdb/influxdb-python#100]
@toddboom 

Hi! Can you please upload 0.2.0 to pypi?

Also, can I have the permissions to upload it? My username on pypi is reazem.

Thanks!

**Comment by ReAzem** [comment]
I have fixed the travis deployment in 30251aecdebd69d2a10306e4356c696d0abcad1c, so 0.2.0 was uploaded to pypi. 

However, if I had permissions on pypi I would disable travis uploads and push signed uploads instead.

**Comment by otoolep** [comment]
I have pinged @toddboom about this. Please note that we are now using Circle CI in the main repo, you might like to check it out.

**Comment by toddboom** [comment]
@ReAzem Ok, I added you as a maintainer on pypi - let me know if you need anything else!

**Comment by ReAzem** [comment]
That should work! Thanks :) I'll check out Circle CI soon.
