### ISSUE TITLE
write_points method fails if called at exactly 5 second intervals

### ISSUE THREAD

**Issue by pddenhar** [influxdb/influxdb-python#103]
I'm experiencing a strange problem with the DB client that has taken a while to wrap my head around. Running a very simple logging script POSTing data to a remote database every five seconds (the five seconds is important), about one in 10 writes will fail throwing an `requests.exceptions.ConnectionError`.

Here is some example code that exhibits this behavior very consistently for me:
```
from influxdb import InfluxDBClient

client = InfluxDBClient('ADDRESS', 8086, 'USERNAME', 'PASSWORD', 'log', timeout=None)
json_body = [{
    "points": [],
    "name": "test.connectivity",
    "columns": ["time", "value", "errortype"]
}]
import time, calendar
while 1:
    inttime = calendar.timegm(time.gmtime())
    json_body[0]["points"].append([inttime, 1, None])
    try:
        client.write_points(json_body)
        print "Write succeeded"
        json_body[0]["points"] = []
    except Exception as e:
        print "Write failed: ", e, type(e)
        json_body[0]["points"][-1][1] = 0
        json_body[0]["points"][-1][2] = str(type(e))
    time.sleep(5)
```

The time.sleep(5) is important, because the following behavior only happens with a delay of five seconds between writes. Four seconds or six seconds don't have any problem. About every one in ten or so requests, the write_points call will throw an exception which prints out like this:
```
Write failed:  HTTPConnectionPool(host='ADDRESS', port=8086): Max retries exceeded with url: /db/log/series?p=PASSWORD&time_precision=s&u=USERNAME (Caused by <class 'httplib.BadStatusLine'>: '') <class 'requests.exceptions.ConnectionError'>
```

After watching the sequence of packets to influxDB in wireshark I've come to the conclusion that this issue is happening because of the way the requests library is being used. 

If requests are sent at a greater than 5 second interval, each request is sent, receives a HTTP 200 OK and then exactly 5 seconds later a FIN, ACK packet arrives from the server closing the TCP connection. Each subsequent request then opens a brand new connection with a SYN before sending the POST. 

For a request interval of less than five seconds, the HTTP requests keep the connection alive and a FIN is never received between database writes. 

If the InfluxDB writing interval is exactly five seconds though (not a seemingly uncommon logging interval) the packet sequence looks like this (two requests, five seconds apart, second one failed):
![screenshot from 2015-02-16 15 44 10](https://cloud.githubusercontent.com/assets/1697414/6219718/fcf97f0a-b5f2-11e4-8e3f-1a0e39564405.png)

To me, it appears that the POST request from influxdb-python and the FIN, ACK from the influxdb server must be in flight at the same time, since the ACK of 402 is the same as the ACK that the remote server sent after the first POST was received and does not include the size of the second packet. Somehow this ends up being interpreted by the python client as an httplib.BadStatusLine which causes the unexpected exception to be thrown. 

I understand that this is quite a complicated bug report for what seems like a simple issue, so thank you for taking the time to look over it. For now I'll just decrease my logging interval to four seconds to avoid this timing issue, but it seems like behavior that should be fixed to avoid trapping unsuspecting users of the client who might think they have connectivity issues or server problems when in reality the issue seems to be a very specific TCP state timing issue.

**Comment by ReAzem** [comment]
Thank you for the detailed bug report! I wonder what we can do about this. Do you have any ideas? Our use of requests seems pretty standard. We might have to send this to the requests team. Or should we create a request session object for every request?

**Comment by pddenhar** [comment]
I was able to reproduce the issue using the requests library alone, so I've reported the bug to them.

As for using the library for the time being, it's hard to say. The behavior seems to get more likely to happen proportional to the latency of the internet connection requests are being made on (more latency == more time for the FIN from the server to be in flight but not received). Unfortunately for me, my use of InfluxDB-python is all on devices with extremely high latency internet connections, sometimes up to seconds. This seems to leave a pretty large window where an HTTP request can be sent out while a FIN is in flight from the server, leading to this BadStatusLine error. 

For now, it might be best to not use a Session and simply make requests directly using `requests.post` or `requests.get`? I honestly can't say for sure that they don't use connection pooling (I'm not experienced with the library) but if so I think it would solve this problem for now. 

A side benefit I've been thinking about is that it also might serve to reduce strain on the Influx server, because every single client would not be keeping TCP connections open at all times, but rather opening and closing them upon calls to `write_points`.

**Comment by ReAzem** [comment]
The session object does not keep a connection open.

From the requests doc:
```
The Session object allows you to persist certain parameters across requests.
 It also persists cookies across all requests made from the Session instance.
```

**Comment by languitar** [comment]
I am also experiencing this issue. Is there any easy workaround?

**Comment by ReAzem** [comment]
@languitar 

Can you try [this](https://github.com/influxdb/influxdb-python/tree/create_new_session_at_request) branch and give us an update please?

**Comment by languitar** [comment]
@ReAzem I can try, but I have no clue how to reliably reproduce the case that I observe. So it might work out or not...

**Comment by kmacrow** [comment]
I'm also having this problem. @languitar tried that branch, no improvement.

**Comment by ReAzem** [comment]
@kmacrow I have pushed a new commit. Can you try again?

This is unrelated to the influxdb-python as this is a requests issue. A fix would be to use an interval longer than 5 seconds.

**Comment by nekto0n** [comment]
We had somehow similar issues with requests, keep-alive and broken connections. We had http client, REST server and IPVS balancer in between:
```
client <-> balancer <-> server
```
After connection being quiet for a while balancer simply forgets about established TCP connection and subsequent request after a long pause results in RST being received on client side. It is the same as in-flight-FIN race being discussed here.
`requests` does it's best to check if TCP connection is still alive - it calls `poll()` with 0 timeout to check connection status upon taking connection from pool, but if client hasn't yet received FIN/RST from server it rightfully assumes that connection can be used and issues HTTP request.

This problem could be worked around by enabling `SO_KEEPALIVE` on socket, but:
  * Race condition would still be possible
  * There's no interface to set in `requests`

Our solution was to setup `HTTPAdapter` in requests so that `connection pool size` is less than `retries count`. This works like this, suppose we have connection pool size = 2 and retries count = 3. We take first connection from pool and request fails with socket error, we take second connection from pool and it fails too, so we create new connection and it works (or doesn't, but that's another case).

I took a look at your implementation and as you don't use retries, so these errors are expected and should be handled explicitly.

**Comment by jove1** [comment]
I wonder if #124 would have any effect?

**Comment by ReAzem** [comment]
> these errors are expected and should be handled explicitly.

I was hoping for another solution, but you are right. I'll push a patch that tries to send the packet for up to three times.

**Comment by nekto0n** [comment]
@jove1 This will put connection back to the pool, but won't close it - so I doubt it will help in this case. (If I'm correct about how `requests` work)
