### ISSUE TITLE
plan to support 0.9

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb-python#104]
Is there any plan to support 0.9 any time soon? 
as can be seen [here](http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html) it is now possible to have top-level key/values for things like `tags` and `timestamp` in the same level that database exists but I cannot find how to do it in current version of influxdb-client.

**Comment by ReAzem** [comment]
For now, you will be able to use this functionnality via the write function (see be476a4628d2505bb91d09fc047dc1d439ce93fc).

**Comment by otoolep** [comment]
@ReAzem -- please reach out to me as needed, to get 0.9 support added to the Python library. I've written a fair amount of Python in my time, so can review coded as needed. 

The API docs, in case you haven't seen them, are here:

http://influxdb.com/docs/v0.9/introduction/getting_started.html

**Comment by ReAzem** [comment]
@otoolep -- Thank you, If I have questions, I'll contact you. Are you available on IRC? I am always on freenode #influxdb as reazem.

@dashesy 
The core functions of the lib now work with 0.9. I am closing I am inviting follow #109 for more details.

**Comment by otoolep** [comment]
Email is best @ReAzem -- I don't tend to be on IRC that much.
