### ISSUE TITLE
DataFrameClient time_precision='ms' does not work

### ISSUE THREAD

**Issue by malaakso** [influxdb/influxdb-python#105]
Specifying time_precision='ms' to e.g. write_points method results in an error
`400: time field must be float but is <nil> (<nil>)`
Using time_precision='m' works.

**Comment by ReAzem** [comment]
That is an error from influxdb or influxdb-python?

Depending on what version of influxdb you are using, supported time precisions may change.

For example, 0.8 supports s, ms, or u and 0.9 supports n, u, ms, s, m, and h.

**Comment by malaakso** [comment]
It's the message string from InfluxDBClientError, sorry for not being specific. The problem is that _datetime_to_epoch doesn't handle the case ms, only s, m and u.

**Comment by ReAzem** [comment]
@malaakso Thank you for the report and the details :)

I have opened a PR for a fix. I'll be waiting a little bit for feedback from the author.
