### ISSUE TITLE
DataFrameClient with 0.9.0

### ISSUE THREAD

**Issue by aviau** [influxdb/influxdb-python#108]
@timtroendle Would you be willing to test the DataframeClient with InfluxDB 0.9.0?

There is influxdb 0.9.0 support in the 0.9.0_support branch.

**Comment by timtroendle** [comment]
I don't have an environment to test at the moment. Maybe @tzonghao could support?

**Comment by gst** [comment]
actually the DataframeClient tests completely fail because there are changes required to handle the changes in the format of the responses  we get from influxdb 0.9.

**Comment by gst** [comment]
well, not completely but nearly : 

```
Ran 11 tests in 0.064s 
FAILED (errors=8)
```

**Comment by aviau** [comment]
This was released
