### ISSUE TITLE
cannot drop database with / in name

### ISSUE THREAD

**Issue by robbyt** [influxdb/influxdb-python#110]
I was able to create a database containing a "/" in the name, and then tried dropping the database- I received this error:

`*** InfluxDBClientError: 400: {"error":"error parsing query: found /, expected ;, EOF at line 1, char 23"}`

(I'm using the latest code from the 0.90 branch)

**Comment by ReAzem** [comment]
see: http://influxdb.com/docs/v0.9/query_language/database_administration.html

> The name must only contain alphanumeric characters, dashes, and underscores. No database must already exist with the given name.

this is new with 0.9.0
