### ISSUE TITLE
query() does not use self._database

### ISSUE THREAD

**Issue by robbyt** [influxdb/influxdb-python#127]
The `query` method does not use `self._database`, which means that I must respecify the database for `.query()` even if this was already set at client instantiation.

https://github.com/influxdb/influxdb-python/blob/0.9.0_support/influxdb/client.py#L221

**Comment by ReAzem** [comment]
This was done on purpose. My reasoning is that system calls such as ```show databases``` don't require a database argument so I didn't want to include database in all queries.

You are not the first that points this out, so I guess its an unexpected behaviour.

**Comment by robbyt** [comment]
@ReAzem thanks for reviewing this so quickly - maybe the other methods that use `query` which don't require a database should explicitly set `database=None`

**Comment by ReAzem** [comment]
@robbyt It wouldn't work because I couldn't make the difference between None and unset.

I could fix this by making default an empty string.
