### ISSUE TITLE
404 Errors in Windows

### ISSUE THREAD

**Issue by fowie** [influxdb/influxdb-python#137]
I've installed python-influxdb on my windows machine running python 2.7.9.  Installation was successful, but issuing any influxDB command results in a 404 page not found error.  The server is accessible and commands work using python-influxdb on Linux, but failed on two different windows PCs, one running Win 8.1 and the other running Windows Server 2008.

C:\InfluxDB>python
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from influxdb import InfluxDBClient
>>> json_body = [
... {
...     "name" : "cpu_load_short",
...     "tags" : {
...             "host": "server01",
...             "region": "us-west"
...     },
...     "timestamp":"2009-11-10T23:00:00Z",
...     "fields": {
...             "value": 0.64
...     }
... }
... ]
>>> client = InfluxDBClient('10.196.212.98', 8086, 'root','root','example')
>>> client.create_database('example')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win-amd64\egg\influxdb\client.py", line 305, in create_database
  File "build\bdist.win-amd64\egg\influxdb\client.py", line 227, in query
  File "build\bdist.win-amd64\egg\influxdb\client.py", line 191, in request
influxdb.client.InfluxDBClientError: 404: 404 page not found

**Comment by ReAzem** [comment]
What version of InfluxDB are you using?

The [README](https://github.com/influxdb/influxdb-python/blob/master/README.rst) should fix your problem. It looks like you are using InfluxDB 0.8 with the wrong InfluxDBClient. If you are using InfluxDB 0.8, you should use ``influxdb.influxdb08.InfluxDBClient``.

**Comment by fowie** [comment]
Wow. Guess I was in the wrong place, right time. My Linux python influx was the old version and both windows PCs were the new version. That fixed it, thanks!

-----Original Message-----

**Comment by ReAzem** [comment]
Have a good day :)
