### ISSUE TITLE
SELECT with GROUP BY a tag return only 1 row

### ISSUE THREAD

**Issue by gst** [influxdb/influxdb-python#143]
If you have a serie with distinct tags value then "SELECT * FROM serie_name GROUP BY a_tag_name" only returns one result : while it should returns one for each distinct serie_name:a_tag_name couple..

it's (I think) all is within the `format_query_response()` function which I have to analyse a bit to see how to handle correctly that..

**Comment by ReAzem** [comment]
> it's (I think) all is within the `format_query_response()` function which I have to analyse a bit to see how to handle correctly that..

This is something I have not tested yet, so you must be right! A test case would be very welcome :)

**Comment by gst** [comment]
> This is something I have not tested yet, so you must be right! A test case would be very welcome :)

I've already begun ;)

**Comment by gst** [comment]
Fixer un PR 144
