### ISSUE TITLE
Tighten up format_query_response in client.py

### ISSUE THREAD

**Issue by ptmcg** [influxdb/influxdb-python#149]
- Use dict.get with defaults of [] instead of testing for existence; reduces code nesting levels.
- Use Python zip builtin to stitch columns and values together instead of explicit loop. (May provide some perf benefits too, since zip will run in compiled code instead of current Python loops.)
- sort tags by key - no guarantee what order keys will be returned.

```python
    @staticmethod
    def format_query_response(response):
        """Returns a list of items from a query response"""
        series = {}
        for result in response.get('results',[]):
            for row in result.get('series',[]):
                items = []
                if 'name' in row:
                    name = row['name']
                    tags = row.get('tags', None)
                    if tags:
                        name = (row['name'], tuple(sorted(tags.items())))
                    assert name not in series
                    series[name] = items
                else:
                    series = items  # Special case for system queries

                columns = row.get('columns',[])
                values = row.get('values',[])
                items.extend(dict(zip(columns, value)) for value in values)

        return series
```

**Comment by ReAzem** [comment]
I am already working on a ResultSet object that will improve on this.  It is my priority right now.  Ill

**Comment by ptmcg** [comment]
Will ResultSet support continuous queries?
Can I get a ResultSetIterator or ResultSetGenerator that only gives me records as I pull them, to support any/all/next short-circuiting? (Might internally get in batches of 'n' values, but report 1 at a time)

**Comment by ReAzem** [comment]
>Will ResultSet support continuous queries?

Not yet.

You can take a look at it [here](https://github.com/influxdb/influxdb-python/tree/resultset_try42). It's still very Beta tho...

**Comment by aviau** [comment]
This was released
