### ISSUE TITLE
tutorial_sine_wave.py fails

### ISSUE THREAD

**Issue by tomkcook** [influxdb/influxdb-python#156]
System config:
* Ubuntu 14.04 x86_64
* Python 3.4
* InfluxDB 0.9.0-rc18
* influxdb-python 1.0.2

Attempting to run the tutorial_sine_wave.py programme produces this output:

    python3 tutorial_sine_wave.py 
    Create database: tutorial
    Traceback (most recent call last):
      File "tutorial_sine_wave.py", line 66, in <module>
        main(host=args.host, port=args.port)
      File "tutorial_sine_wave.py", line 35, in main
        client.write_points(data)
      File "/usr/local/lib/python3.4/dist-packages/influxdb/client.py", line 255, in write_points
        retention_policy=retention_policy)
      File "/usr/local/lib/python3.4/dist-packages/influxdb/client.py", line 289, in _write_points
        expected_response_code=200
      File "/usr/local/lib/python3.4/dist-packages/influxdb/client.py", line 200, in write
        expected_response_code=expected_response_code
      File "/usr/local/lib/python3.4/dist-packages/influxdb/client.py", line 191, in request
        raise InfluxDBClientError(response.content, response.status_code)
    influxdb.client.InfluxDBClientError: 500: {"error":"fields required"}

Is there currently a working way to write multiple samples (using the 'columns' and 'points' keys) or are we stuck writing single points, using 'fields' and 'timestamp'?

**Comment by tomkcook** [comment]
But then using the web interface to write this JSON:

    [{
      "name" : "hd_used",
      "columns" : ["value", "host", "mount"],
      "points" : [
        [23.2, "serverA", "/mnt"]
      ]
    }]

which is taken directly from the 'Writing data through HTTP' section of the documentation, also fails, with an HTTP 500.

**Comment by tomkcook** [comment]
I've confirmed that the version of Python involved is not important - the same error happens with Python 2.7.

**Comment by ReAzem** [comment]
Hello!

This tutorial is outdated! Sorry :(

An updated example of the new points format can be found here: http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html

There is also an example in the README of this repo.

I will update tutorial_sine_wave as soon as I find time.

**Comment by ReAzem** [comment]
See https://github.com/influxdb/influxdb-python/commit/120d4db1e32768d8ff911447aab11ce7d6c43a16 . I should commit this soon.

**Comment by tomkcook** [comment]
So, if I've read that right, then to insert multiple points, I have to do this:

    data = [ {
        'name' : 'cpu',
        'tags' : { ... },
        'fields': { 'value': 90 }
      }, {
        'name' : 'cpu',
        'tags' : { ... },
        'fields': { 'value': 80 }
      }, {
        'name' : 'cpu',
        'tags' : { ... },
        'fields': { 'value': 70 }
      }
    ]
    client.write_points(data)

Is that right?  If so, it seems rather a step back from the old way:

    data = [ {
        'name' : 'cpu',
        'tags' : { ... },
        'columns' : { 'value' },
        'points' : [ [90], [80], [70] ]
    } ]
    client.write_points(data)

Or am I missing something?

**Comment by otoolep** [comment]
That is not quite right @tomkcook. Take a look at:

http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html#writing-multiple-points

to see how to write multiple points in one POST, and if the `tags` are the same, they can be pushed up to the top of the batch, reducing the size of the POST body.

**Comment by tomkcook** [comment]
Okay, but the series name and column names have to specified for every sample?  Also, it seems precision has to be specified for every sample (in InfluxDB 0.9.0-rc20, at least).

**Comment by otoolep** [comment]
No, as per the link, timestamp details can be common too. The format of that "common" timestamp can be either with precision, or be in RFC3339Nano format.

**Comment by tomkcook** [comment]
Oh, I think I see; so precision has to be specified alongside timestamp.  I can't specify common precision but timestamp per-sample.  Is that right?

**Comment by otoolep** [comment]
That is correct, though I have opened a ticket to fix that: https://github.com/influxdb/influxdb/issues/2207.

**Comment by ReAzem** [comment]
@otoolep What about the serie name? 

Specifying it as a common attribute got me "error: bucket name  required"

**Comment by ReAzem** [comment]
@tomkcook as of 3ab875aa70b117208746d3b21f76ae038e7cf657, you can easily write top-level tags with write_points.

**Comment by ReAzem** [comment]
Fixed in 941b5eb45647e03038b50a28f63580a088723349
