### ISSUE TITLE
Bug in influxdb client for python

### ISSUE THREAD

**Issue by balookrd** [influxdb/influxdb-python#159]
Exception in thread Thread-9:

Traceback (most recent call last):

File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner

self.run()

File "/usr/lib/python2.7/threading.py", line 505, in run

self.__target(*self.__args, **self.__kwargs)

File "/usr/lib/python2.7/multiprocessing/pool.py", line 376, in _handle_results

task = get()

TypeError: ('__init__() takes exactly 3 arguments (2 given)', <class 'influxdb.influxdb08.client.InfluxDBClientError'>, ("400: invalid character '\\r' in string literal",))

**Comment by balookrd** [comment]
patch for influxdb8.client.py:
--- client.py.orig<---->2015-04-13 15:35:44.000000000 +0300
+++ client.py<->2015-04-14 12:54:40.180442915 +0300
@@ -20,7 +20,7 @@
.
 class InfluxDBClientError(Exception):
     "Raised when an error occurs in the request"
-    def __init__(self, content, code):
+    def __init__(self, content, code=-1):
         super(InfluxDBClientError, self).__init__(
             "{0}: {1}".format(code, content))
         self.content = content

**Comment by balookrd** [comment]
patch for influxdb.client.py:
--- client.py.orig<---->2015-04-13 15:35:44.000000000 +0300
+++ client.py<->2015-04-14 12:57:04.995125210 +0300
@@ -18,7 +18,7 @@
.
 class InfluxDBClientError(Exception):
     """Raised when an error occurs in the request"""
-    def __init__(self, content, code):
+    def __init__(self, content, code=-1):
         if isinstance(content, type(b'')):
             content = content.decode('UTF-8', errors='replace')
         super(InfluxDBClientError, self).__init__(

**Comment by ReAzem** [comment]
Hello @balookrd 

Can you please give me more details about what happened?

**Comment by balookrd** [comment]
Hi! I use InflixDB 0.8.8 and periodically the server returns me an error 400, but the code of the driver doesn't receive the error state number, and tries to create an exception with 2 parameters, instead of 3.
