### ISSUE TITLE
spurious failed test in travis

### ISSUE THREAD

**Issue by gst** [influxdb/influxdb-python#169]
tried to reproduce without success actually..

======================================================================
FAIL: Tests warning for an invalid bulk size.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/savoirfairelinux/influxdb-python/tests/influxdb/influxdb08/helper_test.py", line 171, in testWarnBulkSizeZero
    .format(WarnBulkSizeZero))
nose.proxy.AssertionError: 5 != 1 : <class 'tests.influxdb.influxdb08.helper_test.WarnBulkSizeZero'> call should have generated one warning.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): host
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (2): host
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (3): host
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
Ran 172 tests in 41.485s
FAILED (SKIP=28, failures=1)
ERROR: InvocationError: '/home/travis/build/savoirfairelinux/influxdb-python/.tox/pypy3/bin/nosetests -v'

**Comment by gst** [comment]
I'm trying to investigate this ..

**Comment by aviau** [comment]
Looks like this no longer happens.

Also, I have fixed most flaky tests issues in 78e5adad441767361bcc1a85393140a984394f1a
