### ISSUE TITLE
Client silently fails to write data

### ISSUE THREAD

**Issue by jcelliott** [influxdb/influxdb-python#174]
This could be just a misunderstanding on my part, but I can't get the client to save any data.

I can talk to the server with, e.g., `get_list_series`, but when I follow along with [this example](http://influxdb-python.readthedocs.org/en/latest/include-readme.html#examples) I always get an error on the `query` call:

    InfluxDBClientError: 400: Couldn't find series: cpu_load_short

As far as I can tell, the `write_points` call succeeds (no exception, returns True). Calling `get_list_series` confirms that the series doesn't exist. Any ideas?

**Comment by ReAzem** [comment]
This is me trying the example:
```
>>> from influxdb import InfluxDBClient
>>> json_body = [
...     {
...         "name": "cpu_load_short",
...         "tags": {
...             "host": "server01",
...             "region": "us-west"
...         },
...         "timestamp": "2009-11-10T23:00:00Z",
...         "fields": {
...             "value": 0.64
...         }
...     }
... ]
>>> client = InfluxDBClient('localhost', 8086, 'root', 'root', 'example')
>>> client.create_database('example')
>>> client.write_points(json_body)
True
>>> result = client.query('select value from cpu_load_short;')
>>> print("Result: {0}".format(result))
Result: ResultSet({'(u'cpu_load_short', None)': [{u'value': 0.64, u'time': u'2009-11-10T23:00:00Z'}]})
>>> print client.get_list_series()
[{'name': u'cpu_load_short', 'tags': [{u'host': u'server01', u'_id': 1, u'region': u'us-west'}]}]
>>> 
```

What version of InfluxDB are you using?

**Comment by jcelliott** [comment]
I'm using InfluxDB v0.8. I guess the example only works with v0.9? After changing the payload to match [the influxdb docs](http://influxdb.com/docs/v0.8/api/reading_and_writing_data.html#writing-data-through-http) it worked fine.

It seems like the documentation should be changed for this library. The readme mentions the legacy support; but because the `InfluxDBClient` class name is the same, and the class API is the same, I assumed that the payload should be the same. After looking through the code I realized it wasn't doing any sort of processing to convert the payload, and changed my request accordingly. I guess someone more familiar with InfluxDB would have realized that sooner.

Also, isn't it confusing that the default client for this library supports the **pre-release** v0.9 and the "legacy" client supports the **latest stable** version of influx?

**Comment by ReAzem** [comment]
This is well documented in the README. The 0.8 API is no longer supported upsteam so it is best to use 0.9 for future projects. Maybe it is best that you discovered it now because it will save you the energy of migrating to 0.9

If you have a concrete suggestion to improve the docs, I am willing to merge it.
