### ISSUE TITLE
from_DSN won't work with upper case passwords

### ISSUE THREAD

**Issue by AxelVoitier** [influxdb/influxdb-python#176]
Hello,

If the password given in the dsn string to InfluxDBClient.from_DSN contains some upper case letters, then subsequent queries on the client will fail with:
```
  File "/usr/local/lib/python2.7/site-packages/influxdb/influxdb08/client.py", line 419, in query
    chunked=chunked)
  File "/usr/local/lib/python2.7/site-packages/influxdb/influxdb08/client.py", line 447, in _query
    expected_response_code=200
  File "/usr/local/lib/python2.7/site-packages/influxdb/influxdb08/client.py", line 255, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.influxdb08.client.InfluxDBClientError: 401: Invalid username/password
```

Good practice for passwords is to mix lower and upper cases.
I guess other params like username and database name in the dsn could also have this problem if they are case sensitive as well. I did not test them.

For the moment it can be solved by giving the password as an extra parameter to from_DSN. But it could confuse other users and take them a while to understand.

Cheers,
Axel

**Comment by ReAzem** [comment]
@AxelVoitier The issue should be fixed in the master branch. Thank you for the detailed bug report!
