### ISSUE TITLE
Documentation is wrong for influx08

### ISSUE THREAD

**Issue by kespindler** [influxdb/influxdb-python#177]
The docs say that

```
json_body = [
    {
        "name": "cpu_load_short",
        "tags": {
            "host": "server01",
            "region": "us-west"
        },
        "timestamp": "2009-11-10T23:00:00Z",
        "fields": {
            "value": 0.64
        }
    }
]
```

is an appropriate blob to send to the server with `client.write_points`. I assume this is true for influxdb 0.9.x. However, with a influxdb 0.8.x client, the method succeeds, but no data is written.

```
[
    {
        "points": [
            [
                12
            ]
        ], 
        "name": "cpu_load_short", 
        "columns": [
            "value"
        ]
    }
]
```

is a blob that works for influxdb 0.8.x. It's doubling confusing that the method succeeds instead of raising an error.

**Comment by ReAzem** [comment]
Hello,

The influxdb08 client won't raise an exception unless InfluxDB returns an error. There is no client-side validation of the points.

The docs available in this repo are not for the legacy client. However, they are still available [here](https://github.com/influxdb/influxdb-python/tree/v0.4.1).

The legacy client is not really intended for new users. I keep supporting it for projects that are already in production with 0.8.

From the InfluxDB readme:
> please develop against the current 0.9.0 RCs for new projects that won't go into production for a little bit.

If you have suggestion on how to improve the docs, I will gladly review a pull request.
