### ISSUE TITLE
is support async?

### ISSUE THREAD

**Issue by rfyiamcool** [influxdb/influxdb-python#181]
is support async and batch send ?

**Comment by ChristopherRabotin** [comment]
Batch sending is supported via the `batch_size` `Meta` class attribute in `SeriesHelper`, cf. the [annotated example](http://influxdb-python.readthedocs.org/en/latest/api-documentation.html#serieshelper) in the docs.

As for proper async, you could have a look at [celery](https://celery.readthedocs.org/en/latest/) in combination with some kind of queuing system.
