### ISSUE TITLE
get errors when running `examples/tutorial.py`

### ISSUE THREAD

**Issue by trainchou** [influxdb/influxdb-python#182]
InfluxDB: 0.8.8 running in docker container.
python: 2.7.6

> Create database: example
> Traceback (most recent call last):
>   File "example.py", line 65, in <module>
>     main(host=args.host, port=args.port)
>   File "example.py", line 30, in main
>     client.create_database(dbname)
>   File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 431, in create_database
>     self.query("CREATE DATABASE %s" % dbname)
>   File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 308, in query
>     expected_response_code=expected_response_code
>   File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 257, in request
>     raise InfluxDBClientError(response.content, response.status_code)
> influxdb.client.InfluxDBClientError: 404: 404 page not found

**Comment by georgijd** [comment]
Hi,

It looks like you're using the client for version 0.9. Try using the client for version 0.8.x instead, i.e. change the import statement to:
`from influxdb.influxdb08 import InfluxDBClient`
I think the tutorials assume you're running InfluxDB 0.9.

**Comment by ReAzem** [comment]
I can confirm. The most important difference is going to be the points. Use this format instead: http://influxdb.com/docs/v0.8/api/reading_and_writing_data.html

However, I don't suggest using InfluxDB 0.8 for new projects. From the InfluxDB README:
> current builds have an API that should not change significantly between now and the final 0.9.0 release. Most of the work we're doing now is focused on features and stability for clustering. So please develop against the current 0.9.0 RCs for new projects that won't go into production for a little bit.

**Comment by georgijd** [comment]
In addition to my previous comment, if you're choose InfluxDB v0.9 over v0.8.8, you can still run it in a container by using different tag:
`docker run -d -p 8083:8083 -p 8086:8086 --expose 8090 --expose 8099 tutum/influxdb:staging-0.9.0-rc`

**Comment by trainchou** [comment]
I update to v0.9 and everything is ok now. Thank you  :)
