### ISSUE TITLE
include nanosecond precision for write_points method

### ISSUE THREAD

**Issue by kpweiler** [influxdb/influxdb-python#185]
According to the documentation, the new 0.9.0 release will include support for nanosecond time precision:

http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html#time-format

the write_points method will need to support a new time_precision parameter (maybe with 'n' for nanosecond?)

**Comment by ReAzem** [comment]
It [looks like](https://github.com/influxdb/influxdb-python/blob/master/influxdb/client.py#L376) ``n`` is already accepted.

**Comment by kpweiler** [comment]
Ah, I see it in the current code. I was looking at the code for release 2.3.0 (which does not have it).
