### ISSUE TITLE
Deleting series

### ISSUE THREAD

**Issue by alexvassel** [influxdb/influxdb-python#187]
http://influxdb-python.readthedocs.org/en/latest/api-documentation.html?highlight=delete_series#influxdb.InfluxDBClient.delete_series

Official documentation (for 0.9) does not say anything about how should this function work; but, experiments show, that it expects series id, not series name. It is working with series name for version 0.8 (http://influxdb.com/docs/v0.8/api/query_language.html#deleting-data-or-dropping-series).

**Comment by aviau** [comment]
You are right, the current code does not work. I am updating it right now and adding a test.

**Comment by aviau** [comment]
Waiting on travis

**Comment by alexvassel** [comment]
Thanks)

**Comment by aviau** [comment]
Thank you for the bug report :)
