### ISSUE TITLE
influxdb.client.InfluxDBClientError: 200: 

### ISSUE THREAD

**Issue by svetomir** [influxdb/influxdb-python#189]
Hi,

I am using influxdb (2.3.0) client with Python 3.4.3

When I write data to InfluxDB 0.9 I get error - influxdb.client.InfluxDBClientError: 200. 
![error](https://cloud.githubusercontent.com/assets/6276860/7772795/b96eef92-00a0-11e5-871d-93cf9569a113.JPG)

However, data is written correctly in InfluxDB.

Also, the same script works fine with influxdb (2.1.0 and 2.2.0) client and Python 3.4.3
I also copy-pasted JSON file (I tried to write in with client) to the browser and it was written successfully to Influx.

Please let me know if you need more info or something else.
I am more than happy to help.

Also, thanks for your work.

Svetomir

**Comment by aviau** [comment]
@svetomir Hello :)

The HTTP return codes changed in 0.9.0-rc30 what RC version of InfluxDB are you using?

If you update to 0.9.0-rc30, everything should work as expected.

**Comment by svetomir** [comment]
Hi,

I was using InfluxDB 0.9.0-rc29, upgraded to rc31.
Works as expected.

Thanks ;)
