### ISSUE TITLE
Multiple query request to same  series creates a bad ResultSet  

### ISSUE THREAD

**Issue by adventures91** [influxdb/influxdb-python#192]
When sending multiple queries in the same request it can result in a bad ResultSet when querying from the same series.

For instance if I run these two queries in the same request:

<code>
"select * from foo where time > now() - 20; select * from foo where time < now() - 40"
</code>

I believe it is because the ResultSet uses the series name as the key meaning that both these query results can't be in the ResultSet.

**Comment by aviau** [comment]
Multiple queries should return a list of ResultSets, what would you think of that?

**Comment by adventures91** [comment]
That sounds like a reasonable solution to me

**Comment by aviau** [comment]
I don't have much time right now, so I am taggins this as help-needed.

**Comment by aviau** [comment]
Should I always return a list of ResultSets? Or should I only return a list when there is more than one ResultSet? I think it will be less error-prone if I always return a list.
