### ISSUE TITLE
Update examples: name to measurement

### ISSUE THREAD

**Issue by koppor** [influxdb/influxdb-python#193]
According to issue https://github.com/influxdb/influxdb/issues/2564, the `name` field has been renamed to the `measurement`field.

The current examples give the output "missing measurement".

I know, it's trivial, but starting users might get confused when starting to try the python library.

**Comment by defreng** [comment]
Thank you, ran into this problem :-)

**Comment by aviau** [comment]
There is much more than examples to update.

As you can see in influxdb/influxdb#2564, the update didn't work for me and this is why I didn't update the library.

I'll with 0.9

**Comment by aviau** [comment]
This was fixed in master
