### ISSUE TITLE
Multiple queries with a series that doesnt exist shouldn't throw an exception

### ISSUE THREAD

**Issue by adventures91** [influxdb/influxdb-python#201]
When querying multiple series if one of the series does not exist it throws an exception and you cant get any results.

Some series are based off of continuous queries that may not have run yet. So I cant really know if the series exist yet without multiple queries to the database to first check if a given series exists.

I am not sure of the best solution to this but I don't think the client should throw an exception for this specific error case.

**Comment by aviau** [comment]
This is an interesting issue.

I think that it is expected that the library raises exceptions when InfluxDB returns errors.

However, I could add an option that ignores errors but makes them available for you to read. 

```
results = client.query("select * from this; select * from that", ignore_errors=True)
error_1 = results[0].error
```

``result.error`` would be None when there are no Errors

What do you think?

**Comment by adventures91** [comment]
This seems like a good solution to me it solves the problem I was having and makes it so users can do there own error handling if need be.
