### ISSUE TITLE
All examples have `timestamp` as a parameter, where as of v0.9 it's `time`.

### ISSUE THREAD

**Issue by jmoses** [influxdb/influxdb-python#203]
Ideally the driver should detect the version of Influx it's connecting to, and raise a ValueError on key's that it doesn't expect.

At the very least the docs should be updated for v0.9.

**Comment by aviau** [comment]
> Ideally the driver should detect the version of Influx it's connecting to

I am not interested in doing this. We support 0.8 as legacy but there is no point in supporting 0.9 release candidates.

**Comment by jmoses** [comment]
Sure, that makes sense, but (in my opinion) the driver should raise an error if I give it keys that aren't valid for the current release version of Influx.  If I can get time to dive into the deeper level stuff, I may try and put a PR together.

**Comment by aviau** [comment]
Thanks!

I will close this as this was fixed in e62ce773a9bf7dc196e0b506ebd8067a1a720187
