### ISSUE TITLE
Does the python client support Continuous Queries?

### ISSUE THREAD

**Issue by sartaj10** [influxdb/influxdb-python#207]
Hi 

Does the python client for influxdb support Continuous Queries?

Thanks

**Comment by georgijd** [comment]
Hi,

The [InfluxDBClient.query](http://influxdb-python.readthedocs.org/en/latest/api-documentation.html#influxdb.InfluxDBClient.query) method allows you to send any valid InfluxDB query to the server, so there's no reason for the continuous queries to not work.

**Comment by aviau** [comment]
If you have any specific needs for continuous queries, don't hesitate to post again on this issue.

**Comment by lukaszdudek-silvair** [comment]
AFAIU `InfluxDBClient` doesn't support continuous query management. I've seen #414 - is there any work planned on that again?
