### ISSUE TITLE
Line Protocol: Empty tag value gets converted to a format rejected by InfluxDB server 0.9.1

### ISSUE THREAD

**Issue by junmipan** [influxdb/influxdb-python#215]
A tag in JSON doc as follows:
```
{
    "tags" : {
        "my_tag" : ""
    }
}
```
is converted to line format, by line_protocol.py:make_lines(), as:
my_tag=

This resulted in format error when sent to InfluxDB server.  Should the method convert it to the following instead?
my_tag=""

Or should I simply omit empty tag?

Please advise.

**Comment by aviau** [comment]
>  Should the method convert it to the following instead?

Yes. I think so.

I'll fix it, thanks!
