### ISSUE TITLE
Data writing format

### ISSUE THREAD

**Issue by dschallis** [influxdb/influxdb-python#217]
I noticed that influxdb-python sends JSON to the /write endpoint of InfluxDB.

From Influx's current documentation (0.9), it only describes a line based format (and mentions that JSON is deprecated).

Will this module switch to using the line based format at some point? (though maybe I've just missed some documentation about InfluxDB's JSON protocol still being active)

**Comment by aviau** [comment]
The JSON API still works.

There is support for the line API on the master branch of this repository. 

It will be in the next release of the lib.

**Comment by dschallis** [comment]
Awesome, good to know.
