### ISSUE TITLE
Formats accepted for 'time' field?

### ISSUE THREAD

**Issue by dschallis** [influxdb/influxdb-python#219]
I've been converting some old calls I had using 'curl' to using the influxdb module instead.

One thing I've noticed is that if I use microsecond timetamps (as microseconds since epoch), the data I send using `write_points` results in a 204 response from the server, but doesn't result in the data being stored.  E.g., the following gets a 204 response, but doesn't actually store the point:

    client = InfluxDBClient(...)
    data = [                                                                        
        {                                                                           
            'measurement': 'temperature',                                           
            'tags': {                                                               
                'machine': 'unit42',                                                
                'type': 'assembly',                                                 
            },                                                                      
            'time': 1437996612064194,                                               
            'fields': {                                                             
                'external': 25,                                                     
                'internal': 37,                                                     
            },                                                                      
        }                                                                           
    ] 
    client.write_points(data, time_precision='u')

Changing to `'time': "2015-07-27T12:30:12.64194Z"` works correctly (the docs at https://influxdb.com/docs/v0.9/guides/writing_data.html just mention using time since epoch, so this is the format I've been using in apps so far).

Would be good to document that this shouldn't work from the influxdb module (or ideally throw an error).

**Comment by aviau** [comment]
If InfluxDB didn't store the point and didn't raise any errors, its a bug on the server side.

**Comment by dschallis** [comment]
Yup, could well be. This seems to be fixed in the latest version of your module anyway, so maybe an issue with their JSON handling? (since the line format works perfectly)

**Comment by aviau** [comment]
If its fixed with the line protocol, I wouldn't even submit a bug to InfluxDB as the JSON protocol is to be deprecated.
