### ISSUE TITLE
Is the new line protocol supported?

### ISSUE THREAD

**Issue by ITDebicki** [influxdb/influxdb-python#222]
On the [influxDB](https://influxdb.com/docs/v0.9/write_protocols/write_syntax.html) site for version 0.9.x the documentation states that the JSON protocol is now deprecated.

Does influxdb-python currently have support for the new line protocol, and if not, is it planned to be added?

**Comment by aviau** [comment]
Yes, it has.

It was released in  ``v2.7.1``. It is used by default.
