### ISSUE TITLE
AttributeError for integer tag values

### ISSUE THREAD

**Issue by vrbala** [influxdb/influxdb-python#225]
When the tag values are of type int (non-string essentially), AttributeError is thrown during conversion of data to line protocol form. The comment https://github.com/influxdb/influxdb-python/commit/28dee66da92bd94cfcff67d379da34c84b33ccb3#commitcomment-12561706 points to the potential cause of the issue. 

This is a stopper for adopting release 2.7.3 version. Please let me know for any more information.

**Comment by aviau** [comment]
Thank you for the bug report. It is now fixed

**Comment by vrbala** [comment]
Thank you @aviau for the quick turn around.
