### ISSUE TITLE
ResultSet is brittle - can't handle queries that select multiple values

### ISSUE THREAD

**Issue by zilman** [influxdb/influxdb-python#228]
QUERY = """SELECT mean(value) as value, host FROM cpu_value WHERE type='percent' AND type_instance='idle' AND time > now() - 10m GROUP BY time(1m), * limit 10"""

resp = client.query(QUERY)

resp

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../venv/lib/python2.7/site-packages/influxdb/resultset.py", line 117, in __repr__
    items.append("'%s': %s" % (item[0], list(item[1])))
  File "../venv/lib/python2.7/site-packages/influxdb/resultset.py", line 110, in get_points
    point
  File "../venv/lib/python2.7/site-packages/influxdb/resultset.py", line 183, in point_from_cols_vals
    point[col_name] = vals[col_index]
IndexError: list index out of range

**Comment by zilman** [comment]
It seems resultset is a convenience function that lets you work comfortably with the raw json response from influx. Except if the raw json response is not exactly like resultset expects it to be it explodes.

One way to trip it up reliably is select two things (SELECT mean(value) as value, host).

**Comment by aviau** [comment]
Thank you for the report! I'll take a look at this and get back to you.

**Comment by aviau** [comment]
Hey!

So, this is the result I am getting from InfluxDB:
```
{
    "series": [
        {
            "values": [
                [
                    "2015-08-10T13:25:00Z",
                    null
                ],
                [
                    "2015-08-10T13:26:00Z",
                    null
                ],
                [
                    "2015-08-10T13:27:00Z",
                    null
                ],
                [
                    "2015-08-10T13:28:00Z",
                    2.34
                ],
                [
                    "2015-08-10T13:29:00Z",
                    2.34
                ],
                [
                    "2015-08-10T13:30:00Z",
                    null
                ],
                [
                    "2015-08-10T13:31:00Z",
                    null
                ],
                [
                    "2015-08-10T13:32:00Z",
                    null
                ],
                [
                    "2015-08-10T13:33:00Z",
                    null
                ],
                [
                    "2015-08-10T13:34:00Z",
                    null
                ]
            ],
            "name": "cpu_value",
            "columns": [
                "time",
                "value",
                "host"
            ],
            "tags": {
                "host": "server01",
                "type_instance": "idle",
                "region": "us-west"
            }
        }
    ]
}
```

As you can see, there are more columns than values!

**Comment by zilman** [comment]
@aviau thanks for you swift response. :+1: 

Whether or not this is a bug in InfluxDB is unclear, it seems more like undefined behavior. 
Try the query from the InfluxDB web UI - it works fine and does the right thing.

"SELECT mean(value) as value, host" explicitly, forces it to bring the host tag with it.

"SELECT *" from what I read is equivalent to:

SELECT ("SHOW TAG KEYS FROM cpu_value")+Value

If you catch my drift. 

Anyway, yes, the host column is just a bunch of nulls - but perhaps ResultSet should be more defensive against unexpected structures like this and simply ignore the junk. What do you think?

**Comment by aviau** [comment]
> - but perhaps ResultSet should be more defensive against unexpected structures like this and simply ignore the junk. What do you think?

I agree! But there is no way to know what value corresponds to what field.

For example:

```
from influxdb import InfluxDBClient
import json

client = InfluxDBClient('localhost', 8086, 'root', 'root', 'example')

resp = client.query('DROP measurement cpu_value')


points = [
    {
        "measurement": "cpu_value",
        "tags": {
            "host": "server01",
            "region": "us-west",
            "type_instance": "idle",
        },
        "fields": {
            "value": 0.64,
            "zzz": 34545,
        }
    },
    {
        "measurement": "cpu_value",
        "tags": {
            "host": "server01",
            "region": "us-west",
            "type_instance": "idle",
        },
        "fields": {
            "value": 2.34,
            "zzz": 34545,
        }
    }

]

client.write_points(points)

QUERY = """SELECT host, mean(zzz) as hello, host, value as value, zzz, host FROM cpu_value"""

resp = client.query(QUERY)
print json.dumps(resp.raw)
```

output:
```
{"series": [{"values": [["1970-01-01T00:00:00Z", 34545]], "name": "cpu_value", "columns": ["time", "host", "hello", "host", "value", "zzz", "host"], "tags": {"host": "server01"}}]}
```

My interpretation of the results would be that the ``host`` field is ``34545``,

That would be false :(

**Comment by aviau** [comment]
This was fixed upstream.
