### ISSUE TITLE
InfluxDBClientError when writing boolean data

### ISSUE THREAD

**Issue by jbillhei** [influxdb/influxdb-python#235]
Error looks like this:

"InfluxDBClientError: 400: unable to parse 'sapphire.devices.225 enable_channel_hopping=Falsei 1440436537172820992': invalid boolean"

Note the False is encoded with 'i', as if it were an integer.

In line_protocol.py line 62, _escape_value checks if value is an integer and then appends the i.  Python's boolean type is a subclass of int, so _escape_value will incorrectly append the i.

This is on Python 2.7.6.

**Comment by aviau** [comment]
Thank you for the bug report! I'll fix that right away.

**Comment by aviau** [comment]
Fixed and released to pypi. v2.9.1

**Comment by jbillhei** [comment]
Thanks!!!
