### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by njurgens** [influxdb/influxdb-python#238]
It would be nice if influxdb-python had a changelog detailing the changes between releases.  I would like to be able to easily tell what's changed in a newer version and if I need to or should not upgrade to it.  For example, InfluxDB v0.9.3 introduced a change to how integers are represented in the line protocol.  Because there's no changelog, it's not clear whether influxdb-python v2.9.0 supported this change to the line protocol without looking at the commit log or code.

**Comment by aviau** [comment]
I wouldn't be against a changelog, but the information you are looking for is [here](https://github.com/influxdb/influxdb-python/releases).
