### ISSUE TITLE
Exceptions should be documented

### ISSUE THREAD

**Issue by victorhooi** [influxdb/influxdb-python#245]
I can see there's exceptions in https://github.com/influxdb/influxdb-python/blob/4be0d6a449e1e2131fede8d61751dd87e9f037df/influxdb/exceptions.py

However, these aren't mentioned at all in the documentation. It would be great if the documentation could at least mention the exceptions that can be raised.

**Comment by aviau** [comment]
We just did that in #249 .

We should improve the docstrings if necessary.
