### ISSUE TITLE
six version is pinned to 1.9.0

### ISSUE THREAD

**Issue by dobesv** [influxdb/influxdb-python#252]
Because the `requirements.txt` sets `six==1.9.0`, projects that have multiple dependencies on six that use only a lower bound may fail to run because a newer version 1.10.0 might be installed as a result of processing some other dependency and pip is apparently not clever enough to figure all this out on its own.  Any specific reason why the requirement couldn't be `six>=1.9.0` ?

**Comment by aviau** [comment]
There is no reason, I will fix this right away.

**Comment by aviau** [comment]
fixed in 2.9.2 and pushed to pypi
