### ISSUE TITLE
FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

### ISSUE THREAD

**Issue by aviau** [influxdb/influxdb-python#258]
@tzonghao Can you take a look at this? It has to do with pandas.

This was reported in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802079

**Comment by tzonghao** [comment]
Alex, I won't have access to computer until sometime next week.

________________________________
On: 17 October 2015 17:28, "Alexandre Viau" <notifications@github.com> wrote:

@tzonghao<https://github.com/tzonghao> Can you take a look at this?

-
