### ISSUE TITLE
How to build deb&rpm?

### ISSUE THREAD

**Issue by adeploy** [influxdb/influxdb-python#280]
I'm sorry but can't find any clue about how to build deb&rpm.
Can you support control file to build DEB, and repo file to build RPM?

Thanks

**Comment by aviau** [comment]
Hello, I am not building the RPMS.

The Debian Packaging repository is found here: http://anonscm.debian.org/cgit/collab-maint/influxdb-python.git

**Comment by adeploy** [comment]
Really thanks to that.
But how do you build the deb? As far as I know, we just can use simple command like `python setup.py sdist_rpm` to build debs.
Do you use stdeb? Or with debuild commands?
Thanks.
