### ISSUE TITLE
Parse DSN instead of connection parameters

### ISSUE THREAD

**Issue by thedrow** [influxdb/influxdb-python#52]
It is a very common pattern to allow hostname to be a DSN e.g. 
* influxdb://myuser:mypassword@localhost:8086/databasename
* udp+influxdb://myuser:mypassword@localhost:8086/databasename
* https+influxdb://myuser:mypassword@localhost:8086/databasename

Python provides the urlparse module that can be used to parse DSNs.

**Comment by tupy** [comment]
:+1:

**Comment by ChristopherRabotin** [comment]
Would a static method suit? It could be used as follows and would return an InfluxDBClient instance: `InfluxDBClient.from_dsn(dsn)`.

If there's no objection, I'll start handling this minor change soon.

**Comment by tupy** [comment]
See the Sentry client implementation:
https://github.com/getsentry/raven-python/blob/133fcdb74869bb270f75642889b17b0752bf0b6e/raven/base.py#L122

**Comment by ChristopherRabotin** [comment]
Thanks for the link. I'll stick with the `from_DSN` function so as to not modify the signature for the InfluxDB client, which may lead to breaking changes for all current users.

**Comment by ReAzem** [comment]
Closed in #153

Thanks to @ChristopherRabotin

**Comment by thedrow** [comment]
Thank you!
