### ISSUE TITLE
Document batch_size for write_points

### ISSUE THREAD

**Issue by analytically** [influxdb/influxdb-python#65]
This is currently not documented. Also state that the data needs to be part of kwargs, since write_points(data, batch_size=10000) won't work.

**Comment by ChristopherRabotin** [comment]
I think the documentation has been written up already: https://github.com/influxdb/influxdb-python/blob/master/influxdb/influxdb08/client.py#L211 . Do you confirm?

**Comment by gylu** [comment]
@analytically, I'm a little bit slow, but wouldn't write_points(data, batch_size=10000) work, because kwargs would get it?
